# Generated by Django 3.1.7 on 2021-03-04 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 12, 55, 18, 133308, tzinfo=utc), verbose_name='date_recieved'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_desc',
            field=models.TextField(max_length=400),
        ),
    ]
