# Generated by Django 3.1.7 on 2021-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('item_name', models.CharField(max_length=40, unique=True)),
                ('item_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Punjabi', 'Punjabi'), ('Kathiyawadi', 'Kathiyawadi'), ('Chinese', 'Chinese'), ('Maxican', 'Maxican'), ('Fastfood', 'Fastfood'), ('Beverages', 'Beverages'), ('Dessert', 'Dessert'), ('Bread', 'Bread'), ('Starter', 'Starter')], max_length=15)),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
