# Generated by Django 3.1.5 on 2021-03-20 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField()),
                ('bill_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('total', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('is_printed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BillMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0)),
                ('Bill_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bill.bill')),
                ('Item_Id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.menu')),
            ],
        ),
    ]
