# Generated by Django 3.1.5 on 2021-03-20 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billmenu',
            old_name='Bill_Id',
            new_name='bill_id',
        ),
        migrations.RenameField(
            model_name='billmenu',
            old_name='Item_Id',
            new_name='item_id',
        ),
        migrations.AddField(
            model_name='billmenu',
            name='item_name',
            field=models.CharField(default=datetime.datetime(2021, 3, 20, 11, 29, 53, 487774, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billmenu',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='billmenu',
            name='item_total',
            field=models.IntegerField(default=0),
        ),
    ]
